### ISSUE TITLE
velocity_position_controller branch doesn't build

### ISSUE THREAD

**Issue by brawner** [ros-controls/ros_controllers#102]
I think it's because there are two add_library commands. @davetcoleman what did you do?!

**Comment by davetcoleman** [comment]
Sorry, I merged `hydro-devel` and it caused this bug. I then fixed it locally when I found it, but I never pushed. 

Fixed:
https://github.com/ros-controls/ros_controllers/commit/94b5853399a843a070343f9e9b11f8e16a33bc31
