### ISSUE TITLE
Thoughts on composite controllers?

### ISSUE THREAD

**Issue by jbohren** [ros-controls/ros_controllers#12]
A while back I put some composite controllers together for adding the outputs of controllers together by just making a controller into a hierarchical structure. It works with un-modified ros_control.

https://github.com/jhu-lcsr/composite_controllers

Any feedback is welcome!

**Comment by davetcoleman** [comment]
I'm going to assume you've given up on this feature? Should this issue be closed?

**Comment by jbohren** [comment]
Yes, and yes.

**Comment by maxpolzin** [comment]
It is a pity you gave up on this. Now I have to create my own composite controller (effort+velocity), by implementing a new controller for ros_control.

**Comment by jbohren** [comment]
:+1: necromancer.

> Shouldn't it be better effort_average, instead of effort_sum in your example of a composite controller?

The motivating use case here was combining an inverse dynamics controller with some other effort controller, hence the sum.

> It is a pity you gave up on this. Now I have to create my own composite controller (effort+velocity), by implementing a new controller for ros_control.

It quickly became apparent that I needed something more sophisticated, so I ended up using Orocos RTT, and built up this framework:

https://github.com/jbohren/conman

**Comment by maxpolzin** [comment]
Thanks a lot for the explanation. 
And thanks for pointing me to the other framework.
