### ISSUE TITLE
trajectory_interface includes missing from .deb install?

### ISSUE THREAD

**Issue by skohlbr** [ros-controls/ros_controllers#122]
When trying to implement a specialization of the JointTrajectoryController, I want to use `trajectory_interface::QuinticSplineSegment<double>` for one of the template parameters. It appears the whole `trajectory_interface` subfolder is missing from the .deb install (12.04/Hydro/AMD64) of `ros-hydro-joint-trajectory-controller`, however. Or am I just overseeing something?

**Comment by bmagyar** [comment]
Hi,
I just checked and it's no wonder that it is missing, the install rule only takes care of "include/joint_trajectory_controller" folder.

https://github.com/ros-controls/ros_controllers/blob/indigo-devel/joint_trajectory_controller/CMakeLists.txt#L93

Make a pull request to change the CMakelists.txt file, then wait for the result. Keep in mind that the debian release system is far from instantaneous, you might want to consider working with a local clone for now.

**Comment by adolfo-rt** [comment]
Standby for PR...
