### ISSUE TITLE
Velocity Position Controller

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_controllers#131]
Greetings,

I've fallen behind in tracking the recent changes to ros_controllers, particularly a velocity-position-controller. My [original attempt](https://github.com/ros-controls/ros_controllers/pull/64) at implementing one last year is very out of date. I'm trying to re-vamp the Baxter controllers that I created all of this for. Here is what I've gleemed just now from lost of Github discussions:

It seems most of the original features were finally merged in:
https://github.com/ros-controls/ros_controllers/pull/117
https://github.com/ros-controls/ros_controllers/pull/116

Except this one:
https://github.com/ros-controls/ros_controllers/pull/115

Which will be replaced by:
https://github.com/pal-robotics/ros_controllers/pull/41

**Question**: can we get the joint_mode_controller merged soon?

@brawner In the meantime, I'm going to remove my branch `velocity_position_controller` since all these features have been replaced, and because, embarrassingly, [I made a bad commit](https://github.com/brawner/ros_controllers/commit/f2f09c2fa4d0ef800f0712a6e53eb49f0dd5ccbb) to it. I have replaced it with a hydro-only version: https://github.com/ros-controls/ros_controllers/tree/hydro-velocity-pos-controller

**Comment by adolfo-rt** [comment]
A proposal for a joint mode interface and controller will be presented for review once validation is complete. The proposal is based on your original PR, but has been extended to take into account additional concerns that were raised during the PR discussion.

**Comment by Karsten1987** [comment]
Is there any update on this?
Ended up here by following [this ros_control tutorial](http://wiki.ros.org/ros_control/Tutorials/Switching%20control%20modes%20in%20hardware). 
Thus the doc seems to be outdated.

**Comment by adolfo-rt** [comment]
What exactly are you looking for?. This issue is a bit out of date, and talks about more than one thing. With luck, what you need has already been merged.

**Comment by Karsten1987** [comment]
I was looking for the joint_mode_interface. I am on indigo and got the impression it's not available. 
Can you confirm that? Again, I am simply following the tutorials, thus I might be doing something wrong.

**Comment by adolfo-rt** [comment]
It is available. It was merged in https://github.com/ros-controls/ros_control/pull/200, indigo-devel. There is no need for a hardware interface or a controller. You add support for mode switching to your robot by specializing the `canSwitch` and `doSwitch` methods of `RobotHW`. At runtime, you simply call the `switch_controllers` service, and any switching that might be required is taken care of by your robot hardware abstraction.

**Important note:** There is a bug in the implementation, which is being discussed in ros-controls/ros_control#211.

@davetcoleman, do you mind if we remove the misleading [tutorial](http://wiki.ros.org/ros_control/Tutorials/Switching%20control%20modes%20in%20hardware)?.

**Comment by davetcoleman** [comment]
No problem - that tutorial was originally copy-pasted from Sachin's Github wiki version, then I added more detail when I implemented the initial controller switching functionality (that was never merged in)

**Comment by toliver** [comment]
I've just removed the outdated tutorial.
