### ISSUE TITLE
Release 0.7.3 into hydro and 0.9.0 into indigo

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_controllers#134]
I'm planning on making a simultaneous release of ros_controllers into hydro (0.7.2 → 0.7.3) and indigo (0.8.2 → 0.9.0) early next week. Prerelease tests are passing on both branches. If there are any bugfixes that you would like to see in these releases, please let me know.

**Comment by bmagyar** [comment]
During this weekend I will bring the diff_drive_controller in indigo-devel up-to-date from the PAL Robotics repos.

**Comment by adolfo-rt** [comment]
https://github.com/ros/rosdistro/pull/6106

**Comment by adolfo-rt** [comment]
The recent batch of releases were

**Hydro:** (out there)
ros_control 0.7.3
ros_controllers 0.7.3

**Indigo:** (in shadow)
control_toolbox 1.13
ros_control 0.9.1
ros_controllers 0.9.1
