### ISSUE TITLE
Add wiki example

### ISSUE THREAD

**Issue by palocziarpad** [ros-controls/ros_controllers#164]
Please provide a configuration example for skid steer.

**Comment by mikepurvis** [comment]
This is not a substitute for proper wiki docs, but Jackal is a full, working, open-source example of a skid steer robot:

https://github.com/jackal/jackal/blob/indigo-devel/jackal_control/config/control.yaml#L5
http://docs.ros.org/indigo/api/jackal_tutorials/html/simulation.html

**Comment by bmagyar** [comment]
Thanks Mike!

**Comment by adolfo-rt** [comment]
@saznetro, it seems that the know-how is out there, but not in the easy-to-find place you're expecting. How do you feel about adding a simple and self-contained example to the ROS wiki from what Clearpath has made available, so others like you can easily find it?. The wiki can be edited by anyone with an account, and we could proof-read your contribution.

**Comment by palocziarpad** [comment]
@adolfo-rt Okay, I will do that.

**Comment by adolfo-rt** [comment]
Your intentions are much appreciated. Ping us back when you have something to review.

**Comment by palocziarpad** [comment]
I have finished it, please review it:
http://wiki.ros.org/diff_drive_controller#Skid_steer

**Comment by bmagyar** [comment]
- Params are showing up again,
- 3 undocumented params documented
- Jackal example added

Nice :+1: !

**Comment by adolfo-rt** [comment]
Good stuff!. @saznetro, thanks for putting the example together, and to @bmagyar for the review.
