### ISSUE TITLE
Proper repository location?

### ISSUE THREAD

**Issue by mikeferguson** [ros-controls/ros_controllers#17]
If we want this to be a "ROS Standard" of sorts, should it probably live under one of the ros-\* organization?

**Comment by davetcoleman** [comment]
Would this be "https://github.com/ros/"? Also, "https://github.com/ros_control/" seems to be available. 

@ahendrix

**Comment by wmeeusse** [comment]
Are you talking about the release repository or the upstream repository?  Standardizing the release repository makes sense.  The upstream repository however can be anyhting/anywhere depending on what the developers happen to like best, and should not be standardized.

**Comment by mikeferguson** [comment]
Whoops, meant to say "organization" not "repository" -- for instance, catkin_debs eventually moved from willowgarage to ros-infrastructure organization when it became more finalized and a real ROS core package.

@davetcoleman I don't think it's core enough to be in the "ros" organization. There isn't currently a "ros-controls" or similar organization (the closest is "ros-planning" which currently has moveit, navigation, and control_msgs among others).

**Comment by davetcoleman** [comment]
I'm not convinced ros-planning is the right place for ros_control, but am more in favor of a new ros-controls organization. @isucan

**Comment by isucan** [comment]
I think we should have a ros-controls organization, and move control_msgs from ros-planning there

**Comment by ahendrix** [comment]
+1.

If I don't hear otherwise, I will proceed with this tomorrow.

**Comment by davetcoleman** [comment]
+1

**Comment by mikeferguson** [comment]
+1

**Comment by ahendrix** [comment]
Done. I've also split control_toolbox and realtime_tools out into their own repositories so that they can be released separately, since they're stable.

**Comment by davetcoleman** [comment]
I updated the rosdistro/hydro/doc.yaml
https://github.com/ros/rosdistro/pull/1065

**Comment by mikeferguson** [comment]
thanks @ahendrix
