### ISSUE TITLE
[rqt_joint_trajectory_controller] Save/restore plugin settings

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_controllers#188]
Remember selected controller manager and controller from last session, and restore them if they are available. This will allow to save some serious mouse clicking.

**Comment by mathias-luedtke** [comment]
I guess you just want to start controllers, but not stop them?

**Comment by adolfo-rt** [comment]
> I guess you just want to start controllers, but not stop them?

Not starting or stopping the controllers themselves. That can be done by `rqt_controller_manager`. 

Currently, if you have a controller in your `rqt_joint_trajectory_controller` plugin, like:
![rqt_selection](https://cloud.githubusercontent.com/assets/1128028/9354029/46f1b9c8-466d-11e5-9792-c74cc30d5cd2.png)

and you`Ctrl+C`, then relaunch `rqt`, what you get is this:
![rqt_no_selection](https://cloud.githubusercontent.com/assets/1128028/9353961/c94efc42-466c-11e5-9d20-26c98927e36d.png)

The proposed behavior restores the controller you had last time, if it's running (or nothing if it's no longer running), so you go back to the first image, with less clicking around.

Restoring the state works also if you have multiple instances of the plugin, so you can now save rqt perspectives where one instance controls say, the right arm, another the head, another a hand.

**Comment by mathias-luedtke** [comment]
Ah, I got confused..
+1 for rqt_joint_trajectory_controller restore :D
