### ISSUE TITLE
Ability to specify namespace of robot_description

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_controllers#19]
In `ros_controllers/effort_controllers/src/joint_position_controller.cpp` the name of the robot description on the parameter server is hard coded. This is not good for multi-robot systems, such as in simulation using Gazebo:

```
if (!urdf.initParam("robot_description")){
```

We need a way to pass a robot_description parameter when starting a controller so that it can be customized. This would need to be done at `initRequest(..)` in

```
ros_control/controller_interface/include/controller_interface/controller.h
```

And then at `loadController(..)` in

```
ros_control/controller_manager/src/controller_manager.cpp
```

**Comment by wmeeusse** [comment]
The model we've been using is that every robot has it's own controller manager, with it's own set of hardware interfaces and it's own set controllers.  In that model, each robot is namespaced, and every robot has a robot_description parameter in its own namespace. I think this model would also transfer to the gazebo world, with a controller manager plugin for each robot that is simulated.

As a second note, we can pass configuration parameters to each controller through the parameter server; it doesn't necessarily need to be passed on by the controller manager. But I'm hoping this won't be necessary if the above model can be applied to your use case.

**Comment by davetcoleman** [comment]
I agree with all of the above.

>  In that model, each robot is namespaced, and every robot has a robot_description parameter in its own namespace. 

The problem is `urdf.initParam()` uses a non-namespaced nodehandle. See [model.cpp](https://github.com/ros/robot_model/blob/groovy-devel/urdf/src/model.cpp#L80)

**Comment by jbohren** [comment]
As an aside, maybe urdf.initParam() could be overloaded to take a nodehandle or namespace string.

**Comment by davetcoleman** [comment]
I agree.

**Comment by wmeeusse** [comment]
+1 for fixing urdf.initParam().

As a workaround for now, you can use the urdf.initString() method in your controllers, and explicitly get the robot_description parameter from the controller manager nodehandle. So you basically implement the correct behavior of initParam() in the controller.

**Comment by davetcoleman** [comment]
Fixed in merge.
