### ISSUE TITLE
rqt_joint_trajectory_controller sliders access for a lot of joints

### ISSUE THREAD

**Issue by guihomework** [ros-controls/ros_controllers#190]
When a controller has a lot of joints (24 for the Shadow robot hand), the size of the sliders is too large and cannot be seen fully on a screen with HD resolution. 
Is it possible to include a slider to go up and down on the list when the lists gets out of screen ?

**Comment by adolfo-rt** [comment]
Please confirm that #193 fixes your issue.

BTW, it's great that you're testing the plugin under new scenarios, such as many joints or multiple controller managers with same-name controllers.
