### ISSUE TITLE
rqt_joint_trajectory_controller does not update joint list if controller names are identical

### ISSUE THREAD

**Issue by guihomework** [ros-controls/ros_controllers#191]
In the case two controller manager each in a different namespace exhibit each a controller with same name (but controlling different joints for instance left and right arm), the switching to the second controller on the second controller manager does not update the joint list and hence forbid to control the second controller's targets.

Work around could be to name the controller differently. But we already use namespace to run two separate robots (two control loops = two controller manager). 

```
/left/controller_mananger
/right/controller_manager 
```

running an `arm_joint_trajectory_controller`
calling them `left_arm_joint_trajectory_controller` would be redundand information and adding complexity to the deployment and usage.

How to reproduce. Have two controller managers on two namespaces and load a joint_trajectory_controller on each of them with the same name

open rqt_joint_trajectory_controller, 
select first controller_manager, list of controller is updated showing one controller.
select the controller, joint list is updated
select second controller_manager, list of controller remains the same (controller name being the same)
select the controller, joint list is NOT updated, probably because the on_change is not triggered on the controller combobox due to same name. 
Works if there are more than one controller in the controller manager. Or other controller managers that do not show the same controller name.

**Comment by adolfo-rt** [comment]
Thanks for reporting. Please confirm that #192 fixes your issue.
