### ISSUE TITLE
non-conventional control-error sign direction

### ISSUE THREAD

**Issue by bobholmberg** [ros-controls/ros_controllers#2]
As a new user of the position and velocity controllers, I was confused by the non-conventional sign of the controller error term in the position and velocity controllers.  I would expect the controller error to be defined as (reference - actual) or (desired - actual) as is shown in the "PID_control" entry of wikipedia ((http://en.wikipedia.org/wiki/PID_controller)); and standard textbooks including  http://books.google.com/books/?id=EFgOQABEBjIC  and  http://books.google.com/books?id=vlMl-j_cWW4C.

Correcting the sign of these controller error terms to conventional use would also require changing the sign of the error terms in ros_control/control_toolbox/src/pid.cpp to keep the standard use of positive controller gains.

If there is a reason for not using what appears to be the dominant sign convention in robotics, we should add comments as to why this choice of control error signs is made in this code and in the API documentation.

**Comment by jbohren** [comment]
Yeah, the error, `p_error_` shown [here](https://github.com/willowgarage/ros_control/blob/master/control_toolbox/src/pid.cpp#L143) and computed [here](https://github.com/willowgarage/ros_controllers/blob/master/effort_controllers/src/joint_position_controller.cpp#L129) for different types of joints, is also not what I would expect. Based on the [old svn logs](https://code.ros.org/trac/wg-ros-pkg/browser/pkg/trunk/controllers/control_toolbox/src/pid.cpp?rev=4454) it was Stu who originally wrote this. Maybe he could shed some light on it if the current maintainers can't?

I think if there were ever a good time to change this, it's now.

**Comment by wmeeusse** [comment]
Ya, it's a bit unfortunate that the convention wasn't followed. We thought about changing it a while ago, but there is not really an easy way to do this without causing a lot of pain in porting over existing code. The best solution I can think of is to create an _extra_ update method with a different name, which follows the convention. But then the pid object will have two update methods with different names, which I think is even worse than the current situation.

**Comment by jbohren** [comment]
@wmeeusse How much code would have to be migrated?

If it's too much to migrate, what if we add another parameter in the constructor out of some enum like `ERROR_REF_MINUS_CUR` and `ERROR_CUR_MINUS_REF` which flips the sign. We make the default behavior the current one, but `ROS_WARN()` on construction if people use it, with a deprecation warning?

**Comment by wmeeusse** [comment]
It's hard to get good usage metrics of open source tools, but judging from the controller we use at hiDOF, controllers we've deployed for customers and controllers used at Willow, there are many many users.  We're talking about a very basic building block here. I'd say that breaking and/or deprecating the existing API is not an option. 

Your proposal to add a new update method seems pretty reasonable though. I'd suggest to not touch the existing update method, but to add the new update method with the extra argument, and make the extra argument mandatory.  I know that code-wise there's no difference, but API-documentation-wise it's more clear and more backwards compatible. What do people think about this?

**Comment by jbohren** [comment]
@wmeeusse did you mean to say that my proposal seems reasonable or that your proposal seems reasonable?

**Comment by tfoote** [comment]
Creating the new method and deprecating the old one is probably the
cleanest way to do this.  Using a parameter you could end up with different
code paths interacting in unexpected ways.

On Sun, Feb 3, 2013 at 1:11 PM, Jonathan Bohren notifications@github.comwrote:

> @wmeeusse https://github.com/wmeeusse did you mean to say that my
> proposal seems reasonable or that your proposal seems reasonable?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willowgarage/ros_controllers/issues/2#issuecomment-13054405.

## 

Tully Foote
tfoote@willowgarage.com
(650) 475-2827

**Comment by jbohren** [comment]
@tfoote maybe call the new command "setError" since that's also a bit clearer than "update"?

Elsewhere... http://gazebosim.org/api/dev/classgazebo_1_1common_1_1PID.html#a83ec1335e4e25d1c07ab6f9cf6075dab

**Comment by wmeeusse** [comment]
@jbohren I of course think my own proposal is reasonable, but in my previous comment I was actually talking about your proposal ;-) But, I kind of misread your proposal; I thought you wanted to pass the ERROR_CUR_MINUS_REF and ERROR_REF_MINUS_CUR into the update function.  I like that idea better than passing it into the constructor. So we could end up with the old updatePID(double) method, and a new updatePID(double, ERROR_CUR_MINUS_REF) or udpatePID(double, ERROR_REF_MINUS_CUR) method. 

I feel like we do go a little lightly over deprecating such a basic method, and forcing many people to re-release their code. I much rather find a way to keep the existing code in place; and I think the proposal with an extra argument in the updatePID method satisfies all our needs.

**Comment by jbohren** [comment]
> @jbohren I of course think my own proposal is reasonable, but in my previous comment I was actually talking about your proposal ;-) But, I kind of misread your proposal; I thought you wanted to pass the ERROR_CUR_MINUS_REF and ERROR_REF_MINUS_CUR into the update function. I like that idea better than passing it into the constructor. So we could end up with the old updatePID(double) method, and a new updatePID(double, ERROR_CUR_MINUS_REF) or udpatePID(double, ERROR_REF_MINUS_CUR) method.

Well, I'd still prefer creating a new member function and deprecating the current one, like I've done here: https://github.com/willowgarage/ros_control/pull/12

> I feel like we do go a little lightly over deprecating such a basic method, and forcing many people to re-release their code. I much rather find a way to keep the existing code in place; and I think the proposal with an extra argument in the updatePID method satisfies all our needs.

Well, in the case of deprecating updatePID, at least the only thing that would need to be changed is adding a single minus sign or flipping the terms in the computation of the error. Also, we could deprecate it now, and then keep it around for one or two distribution releases, right?

**Comment by vpradeep07** [comment]
> Well, in the case of deprecating updatePID, at least the only thing that would need to be changed is adding a single minus sign or flipping the terms in the computation of the error.

While I think the option of deprecating `updatePID` could work, I'm a little nervous that the port might not go as smoothly as we'd like.  If someone mistakes the switch to `setError` as just being a function rename, then all of their controllers will suddenly go unstable after porting forward.

Adding in a second argument as in `updatePID(double, ERROR_CUR_MINUS_REF)` would make the functionality change more explicit, and thus reduce the chance of people accidentally making all their controllers go unstable.

**Comment by jbohren** [comment]
@vpradeep07 

> Adding in a second argument as in updatePID(double, ERROR_CUR_MINUS_REF) would make the functionality change more explicit, and thus reduce the chance of people accidentally making all their controllers go unstable.

Yeah, I could see that happening, it could be more explicit. Still it would be nice to be able to deprecate the current error computation at compile time, while not requiring that all future invocations of `updatePID()` require that argument. Also, considering the fact that this isn't just additional data, but is actually changing the behavior of the function, what if we did the following with a default template parameter:

``` c++
    static const enum {
        TARGET_MINUS_CURRENT = 0,
        CURRENT_MINUS_TARGET = 1
    };

    template<int ERROR_SIGN = CURRENT_MINUS_TARGET>
    double updatePID(double error, ros::Duration dt);
```

And then implement specialized template functions:

``` c++
    ROS_DEPRECATED template<CURRENT_MINUS_TARGET>
    double updatePID(double error, ros::Duration dt) { ... }

    template<TARGET_MINUS_CURRENT>
    double updatePID(double error, ros::Duration dt) { ... }

```

So when calling updatePID:

``` c++
    // Gives deprecation warning:
    my_pid.updatePID(current - target, ros::Duration(0.1));
    // Gives deprecation warning:
    my_pid.updatePID<CURRENT_MINUS_TARGET>(current - target, ros::Duration(0.1));
    // Gives no warning:
    my_pid.updatePID<TARGET_MINUS_CURRENT>(target - current, ros::Duration(0.1));
```

**Comment by tfoote** [comment]
That's not really different than just making a new function call, it's just
a templated function call.  Then it leaves you with a much longer call,
with no way to remove the templating in the future without breaking anyone
who hasn't ported.  (Even worse they won't even get a warning if you change
the default.  The warning will go away but the code will break.

If you change the function name, are clear in changelist notes and in code
notes, and documentation such that someone who looks up the deprecation
error must read that the sign has changed they will not have an excuse to
just copy the results.  Because to resolve a deprecation you must lookup in
the documentation what the replacement function is.  And as long as you
make sure that every piece of documentation pointing to the new version of
the function mentions the change in sign the people modifying the code
should see it.

And when you remove the initial version of the function, their code will
stop warning and start erroring.

**Comment by bobholmberg** [comment]
Thanks for working on this, I've been following along.  To add my opinion,
as the person who started this ticket, I like the idea of a new function
with a new name that keeps the calling syntax succinct.

--Bob

**Comment by jbohren** [comment]
@tfoote 

> That's not really different than just making a new function call, it's just
> a templated function call.  Then it leaves you with a much longer call,
> with no way to remove the templating in the future without breaking anyone
> who hasn't ported.  (Even worse they won't even get a warning if you change
> the default.  The warning will go away but the code will break.

Yeah, so scratch that, then.

> If you change the function name, are clear in changelist notes and in code
> notes, and documentation such that someone who looks up the deprecation
> error must read that the sign has changed they will not have an excuse to
> just copy the results.  Because to resolve a deprecation you must lookup in
> the documentation what the replacement function is.  And as long as you
> make sure that every piece of documentation pointing to the new version of
> the function mentions the change in sign the people modifying the code
> should see it.
> 
> And when you remove the initial version of the function, their code will
> stop warning and start erroring.

Yeah, I still like the code in this PR as the best option: https://github.com/willowgarage/ros_control/pull/12

**Comment by wmeeusse** [comment]
Looks like we have a critical mass behind the deprecation proposal. I merged @jbohren 's pull request into the master branch, for release into Hydro. Thanks everyone for the discussion!

**Comment by jbohren** [comment]
@wmeeusse Thanks!

One question though, are we good with the name that I chose for the function? `setError()`?

**Comment by wmeeusse** [comment]
That name sounds good to me.

**Comment by bobholmberg** [comment]
No, let's change the name of the function to something that is oriented towards the user of this package: a controls-person.  As I discussed with @jbohren (sorry, I should put a link to my comments, if I could find my way around github better). A controls user wants to get/compute/update a new command value.  While it is true we are setting an error, there is no reason to call this function just to set an error.  The return value (ie the command value) is why a user want to use this function.   My choices in order of preference:  getCommand, updateCommand, computeCommand.

**Comment by jbohren** [comment]
+1 to `computeCommand()` or `computeFeedback()`

**Comment by bobholmberg** [comment]
+1 to getCommand or computeCommand

If we're the only two with opinions, let's move forward with computeCommand

--Bob

**Comment by jbohren** [comment]
@bobholmberg since the Pid class stores the last command, there's already an accessor called `getCurrentCmd()` which returns `_cmd` so I think "getCommand()" would be too easily confused with that.

**Comment by jbohren** [comment]
@wmeeusse thoughts on `computeCommand()` instead of `setError()`?

**Comment by vpradeep07** [comment]
Wim is travelling and in meetings today and tomorrow, so his response may be a bit delayed.

+1 for `computeCommand()`

**Comment by wmeeusse** [comment]
All pull requests have been merged, thank you guys for all the discussion, input and patches!
