### ISSUE TITLE
Initialize robot position when using velocity controller 

### ISSUE THREAD

**Issue by zfxw0206** [ros-controls/ros_controllers#200]
Does anybody know how to set the initial position of the robot when using gazebo and ros-controller. For me, when I run the gazebo launch file, the robot seems fall down from the sky, and I could not control the initial position of the robot. 
I use position controller to move the model to the position which is what I want, but when I change the controller to velocity controller, the model always move.
So how could I initialize the robot position when I use velocity controller in gazebo.

**Comment by adolfo-rt** [comment]
ros-answers or gazebo-answers are a better place for this kind of non-development questions.
