### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by paulbovbel** [ros-controls/ros_controllers#207]
Can we have an indigo release, to take advantage of https://github.com/ros-controls/ros_controllers/pull/181, among others?

**Comment by mathias-luedtke** [comment]
+1

We are waiting for #170

**Comment by adolfo-rt** [comment]
https://github.com/ros/rosdistro/pull/10491
https://github.com/ros/rosdistro/pull/10492

Oops, need to update rosdistro...

**Comment by adolfo-rt** [comment]
With updated rosdistro:

https://github.com/ros/rosdistro/pull/10497
https://github.com/ros/rosdistro/pull/10498
