### ISSUE TITLE
Hydro Branch?

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_controllers#21]
ros_controls has a hydro-devel but ros_controllers does not yet. should we add it?

**Comment by mikeferguson** [comment]
I think master should actually be renamed hydro-devel (for the most part, ROS repos have no master, just TURTLE-devel)

**Comment by jbohren** [comment]
:+1: for renaming master hydro-devel

**Comment by davetcoleman** [comment]
+1

**Comment by davetcoleman** [comment]
It looks like a hydro-devel branch was created.
