### ISSUE TITLE
Kinetic Release

### ISSUE THREAD

**Issue by DLu** [ros-controls/ros_controllers#212]
Needed for [urdf_tutorial](https://github.com/ros/urdf_tutorial/issues/19). @jacquelinekay

**Comment by bmagyar** [comment]
Waiting for `control_toolbox` to be released, there's some merging to do there once @paulbovbel has reviewed his PR-s.
@efernandez

**Comment by DLu** [comment]
ros-controls/control_toolbox#51 has been fixed, so control_toolbox should be readyish to go.

**Comment by bmagyar** [comment]
`control_toolbox` is released.
`ros_controllers` coming up!

**Comment by bmagyar** [comment]
The initial releases have all been done. Closing...
