### ISSUE TITLE
Support for UR5?

### ISSUE THREAD

**Issue by Chunting** [ros-controls/ros_controllers#220]
Hi, 
Is this controller support for Universal Robot UR5, CB3.2?
or anyone has developed a controller on UR5?

Thanks,
Chunting

**Comment by carlosjoserg** [comment]
Hi @Chunting, yes, I've moved an UR3/CB3.

However, your question is more appropriate for the ROS Industrial organization, this is the main repo: https://github.com/ros-industrial/universal_robot, and particularly the driver I'm using is https://github.com/ThomasTimm/ur_modern_driver (it requires some ros-indsutrial packages, and probably will be transfered to ros-industrial in the future, see https://github.com/ThomasTimm/ur_modern_driver/issues/18).

Best
Carlos

**Comment by bmagyar** [comment]
Thanks Carlos for answering, I suppose I can close it.

**Comment by Chunting** [comment]
Thank you very much, you two are so kind.
I have set up the ur_modern_driver, and it runs well...

Thanks,
Chunting

**Comment by bmagyar** [comment]
Good luck with it :+1: 

Closing the issue :)
