### ISSUE TITLE
How to use joint_trajectory_controller with real physical motor controller?

### ISSUE THREAD

**Issue by littlejohnyang** [ros-controls/ros_controllers#249]
I have successfully used joint position controller to control my motors (using epos_hardware package). However I would like to be able to send a set of joint values at once (a.ka. joint trajectory) rather than a single joint value at a time. However I am still unclear about the link and how to register hardware to link with joint_trajectory_controller. Is there good examples?

Note: For position control, I can see that I just register ActuatorStateInterface, PositionActuatorInterface etc and then rely controller manager to handle the actuators I listed in config/launch files. But I failed to see how to do it for joint_trajectory_controller. I can't find anybody doing it as well.

**Comment by bmagyar** [comment]
On first blink I don't think you need anything else. Have a look at this config file:

https://github.com/pal-robotics/tiago_simulation/blob/indigo-devel/tiago_controller_configuration_gazebo/config/joint_trajectory_controllers.yaml
