### ISSUE TITLE
diff_drive_controller exports library but not headers

### ISSUE THREAD

**Issue by mistoll** [ros-controls/ros_controllers#257]
The diff_drive_controller package does export the library. But it does not export the headers.

https://github.com/ros-controls/ros_controllers/blob/d8d87cddd5bf9f3abbd8ed64bd1dc4a76969794e/diff_drive_controller/CMakeLists.txt#L13

The headers would be usefull to create derived controllers.
The clearpath fork does export the headers.

**Comment by mathias-luedtke** [comment]
@bmagyar: did you forget about https://github.com/ros-controls/ros_controllers/pull/242#discussion_r90185576?

**Comment by bmagyar** [comment]
Apparently yes. 
I'll fix it right away & put in a release.
