### ISSUE TITLE
Pause and Resume with Joint Trajectory Controller

### ISSUE THREAD

**Issue by littlejohnyang** [ros-controls/ros_controllers#272]
What is the best way to implement pause and resume functionalities with Joint Trajectory Controller? I assume I can add a subscriber in the controller for pause/resume command. But will I be able to stop the motor from moving with the realtimegoalhandle?

**Comment by bmagyar** [comment]
It's not a common theme. I suppose you could save the trajectory status and continue executing it but your velocity and acceleration profiles would be off from the original so it won't guarantee smooth movements.

Check this one out:
http://wiki.ros.org/joint_trajectory_controller/UnderstandingTrajectoryReplacement

What do you mean stopping the motor with a realtimegoalhandle?
