### ISSUE TITLE
build error | the setGains() function do not have a antiwindup argument

### ISSUE THREAD

**Issue by Booooooosh** [ros-controls/ros_controllers#281]
When building effort controllers (the joint_velocity controller), it seems that the call to the pid_controller.setGains(p, i,d, i_max, i_min, antiwindup) filed due to the corresponding function within the module that locates inside the control_toolbox did not have a argument antiwindup.

There is actually a pull request here: #214 
I am using the ROS Indigo and Ubuntu 14.04, does anyone face the same question?

Many thanks!

**Comment by bmagyar** [comment]
You overlooked the branch you are compiling from. The PR you referenced is against ROS Kinetic. Get the `indigo-devel` and you'll be fine. In case you don't need to modify the controllers you could also just install everything with `apt-get install ros-indigo-ros-control*`

**Comment by Booooooosh** [comment]
That's true, sorry for the confusion.
