### ISSUE TITLE
joint_trajectory_controller - Always dropping first trajectory point

### ISSUE THREAD

**Issue by agutenkunst** [ros-controls/ros_controllers#291]
If a trajectory has no specified start time (0) and time_from_start of the first point is zero the first point will always be dropped. 

Changing
https://github.com/ros-controls/ros_controllers/blob/3ee947a8a51f0a7594e54b2a79b95bc01d1591dc/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_msg_utils.h#L57
< to <= stops this behaviour.

Not sure if this would be the best fix.

Any comments?

**Comment by bmagyar** [comment]
Yes as that'd leave no time for your arm to make it to the first point. Better to fill `time_from_start` for the first point too.

**Comment by mathias-luedtke** [comment]
`time_from_start == 0` just holds for the starting point of a trajectory, if any.
And this starting point should better match the actual position of the actuator ;)

**Comment by agutenkunst** [comment]
Just noticed that using OMPL there will always be the warning that the first point has been dropped which at first sounds like something you would not want a controller todo. Knowing that at time_from_start = 0 state == current_state seems pretty implicit.

**Comment by bmagyar** [comment]
Any update on this?

**Comment by moucrob** [comment]
I agree, still get displayed the warn
`[ WARN] [1532615030.341235239]: Dropping first 1 trajectory point(s) out of 11, as they occur before the current time.
First valid point will be reached in 0.466s.
`
But now the robot at least does the job, thanks!

Edit : 
Here is the strict inequality to modify : 
`/opt/ros/kinetic$ grep -r "return time < point_start_time;" * .[!.]*
`

`include/joint_trajectory_controller/joint_trajectory_msg_utils.h:    `
`return time < point_start_time;`

**Comment by jschleicher** [comment]
I'm working on this during WMD18
