### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-controls/ros_controllers#331]
It looks like all of the dependencies for this package are available in Melodic, so it would be great to get it released there.  Thanks in advance.

**Comment by bmagyar** [comment]
We have issues with one test that fails to build ATM: 
https://github.com/ros-controls/ros_control/issues/305#issuecomment-381353397

Also before releasing this I'd prefer to push through a shift to `std::shared_ptr` everywhere. Or would you prefer a release now (with the fixed test) and API change in 2 weeks?

**Comment by clalancette** [comment]
@bmagyar The main thing this is holding up is `urdf_tutorial`, but I think that can wait another couple of weeks.  So let's hold off until you have the API change done.

**Comment by clalancette** [comment]
This was done, so closing it out.  Thanks!
