### ISSUE TITLE
Cleanup Branches

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_controllers#34]
I'd like to cleanup the branches in this repo, feedback welcomed:

fuerte-dev  --> **fuerte-devel**
fuerte - REMOVE - this is the same as fuerte-dev except behind one commit
groovy --> **groovy-devel**
**hydro-devel** - keep
master - REMOVE - this is behind hydro-devel by a few commits and not really needed

the "devel" name is a standard the ROS community seems to have settled on

**Comment by adolfo-rt** [comment]
OK for me. I'd also add **indigo-devel** for API-breaking development.

**Comment by davetcoleman** [comment]
Yes, we'll need indigo-devel when we start to have api changes, but typically ROS projects don't branch for the next version until the need arises. Feel free to add it when needed.

**Comment by davetcoleman** [comment]
I have renamed the branches as described.
