### ISSUE TITLE
undefined symbol with new release

### ISSUE THREAD

**Issue by JaimeGJ** [ros-controls/ros_controllers#346]
Hi, I've updated effort_controllers and now I can't launch my JointPositionControllers because the path it gives is:

> gzserver: symbol lookup error: /opt/ros/kinetic/lib//libeffort_controllers.so: undefined symbol: _ZN4urdf5Model23initParamWithNodeHandleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN3ros10NodeHandleE

I've tried to install an old version of the pkg but I  don't know how to.

**Comment by bmagyar** [comment]
This is required to support namespaced robot descriptions, it's been added over a year ago [here](https://github.com/ros-controls/ros_controllers/pull/245/files) to the controller and similarly to `urdf` [here](https://github.com/ros/urdf/commit/3384a0a76f6ab02dc01354bdc0e55fe482c29f57). Please also update the `urdf` package. If you get into another undefined symbol issue, I suggest to keep looking up where they come from and update one package at a time. 

Of course if you can afford to update everything, that'd be the simplest option.

**Comment by mathias-luedtke** [comment]
> Of course if you can afford to update everything, that'd be the simplest option.

You should at least update the `urdf` package.. (the function was released in version 1.12.8)

In the future you should avoid updating individual packages and upgrade all packages instead.
The build farm ensures compatibility only for the full set of packages at a time.
And if all catkin workspace needs to be rebuild completely to avoid ABI breaks.
