### ISSUE TITLE
Issue with PosVelJointHandle

### ISSUE THREAD

**Issue by venkisagunner93** [ros-controls/ros_controllers#351]
https://answers.ros.org/question/294212/ros-control-assertion-failed/.
Please have a look at the above ros answers' question. Found this place to be more focused on ros controllers. Hence I'm mentioning my issue here. Thanks !

**Comment by mathias-luedtke** [comment]
Please note that this is an issue tracker and no support forum.
In addition, cross-posts are highly discouraged to keep the discussions more focused.

You've already received a very good answer to your question.
It looks like an issue with your code and `PosVelJointHandle` is dealing with it properly.
I will close this issue now.
