### ISSUE TITLE
joint_current_controller is needed

### ISSUE THREAD

**Issue by itfanr** [ros-controls/ros_controllers#358]
Some servo does not give a effort interface, but give a current interface instead.

So a joint_current_controller is needed which can send sin function to motor driver.

**Comment by bmagyar** [comment]
Thank you! You are welcome to submit a pull request implementing this.

**Comment by itfanr** [comment]
@bmagyar  I am a beginner. But if I am glad to share my code.

**Comment by mathias-luedtke** [comment]
Would the implementation of a current-based controller be different from an effort-based controller?
In `ros_canopen` I have just used the effort interface for the current-based control interface.
`sensor_msgs/JointState` only supports effort anyway..

**Comment by itfanr** [comment]
@ipa-mdl
I will read your [ros_canopen](https://github.com/ros-industrial/ros_canopen) repo and learn to control effort and current.

Thank you.
