### ISSUE TITLE
[diff_drive_controller] Jerk Limits Behave Weirdly when Stopping Robot

### ISSUE THREAD

**Issue by rohbotics** [ros-controls/ros_controllers#359]
With a low jerk limit set the robot goes backward a bit after stopping. 

This is because the jerk limiter is making decisions by taking the 2nd derivative of velocity, so when the robot reaches the target of 0 the jerk limiter forces it to continue the negative acceleration by going backward. 

I would think the right behavior for the controller would be decreasing the acceleration as it approaches target velocity to limit the jerk. This would result in a v/t graph that looks like an s-curve.

**Comment by rohbotics** [comment]
More info:
This is the expected (and actual) behavior with no jerk limits, and only acceleration limits. (infinite jerk)
![image](https://user-images.githubusercontent.com/2825327/45930452-5b31aa00-bf15-11e8-94fa-2813e8a3e352.png)
(Red is Velocity, Black is Acceleration, and Blue is Jerk for all graphs) 


This is the behavior I would expect with jerk limits set. 
![image](https://user-images.githubusercontent.com/2825327/45930395-8798f680-bf14-11e8-94aa-e6b46de83120.png)


The actual behavior is much different, as the jerk limiter causes the velocity to go negative.

**Comment by roncapat** [comment]
@rohbotics How do you solved?
