### ISSUE TITLE
JointTrajectoryController difference kinetic and melodic

### ISSUE THREAD

**Issue by agutenkunst** [ros-controls/ros_controllers#369]
https://github.com/ros-controls/ros_controllers/commit/e6bb3c6323a7ac1c842b43217bd8437b1f11f3bc broke the class interface due to the introduction of a new parameter to `updateTrajectoryCommand`
how about a cherry-pick on this?

Maybe https://github.com/ros-controls/ros_controllers/commit/5ff302aa742c992193fb0c463d1b59a903174aac from @ipa-mdl should also be taken? 

PR desired?

**Comment by mathias-luedtke** [comment]
For clarification: it broke the subclassing interface.
I think back-porting is the only way to make it compatible again.

> PR desired?

IMHO yes :)

**Comment by agutenkunst** [comment]
Applying the same changes in kinetic-devel would work for me. How about that?

**Comment by mathias-luedtke** [comment]
Resolved in #370
