### ISSUE TITLE
four_wheel_steering_controller depends on urdf_geometry_parser

### ISSUE THREAD

**Issue by darkdragon-001** [ros-controls/ros_controllers#398]
`four_wheel_steering_controller` depends on `urdf_geometry_parser`, but I can't find this package. Maybe there is a more suitable package to parse _urdf_ file?

**Comment by mathias-luedtke** [comment]
`urdf_geometry_parser` is released to ` kinetic`  and newer. You can find the source [here](https://github.com/ros-controls/urdf_geometry_parser).
I have just created the missing [wiki page](http://wiki.ros.org/urdf_geometry_parser).

> but I can't find this package

I would recommend to resolve/install dependencies with `rosdep`.
