### ISSUE TITLE
Messages are duplicated

### ISSUE THREAD

**Issue by mikeferguson** [ros-controls/ros_controllers#4]
I just noticed that this repo has a "controller_msgs" package, which is a generic port of the pr2_controller_msgs -- however, it should be noted that the Arm Navigation (and now MoveIt) team have already created a generic port -- which is already released: https://github.com/ros-planning/control_msgs. Perhaps we can use that instead of creating more duplication?

**Comment by jbohren** [comment]
@tfoote is there a policy/procedure for handling these sort of things?

**Comment by wmeeusse** [comment]
We're aware of this, and plan to move all messages into ros planning. This ticket is probably a good place to keep track of the issue.

**Comment by mikeferguson** [comment]
As there are a number of changes underway for the hydro release, I figured I should bump this back to people's attentions. I believe that currently, every message that exists in "controller_msgs" is currently in "control_msgs" (the reverse is very much not true).

**Comment by jbohren** [comment]
Shouldn't these all be made into standards and moved into comon_msgs?

**Comment by mikeferguson** [comment]
It does seem that these are pretty common these days. I would really suggest that we move "control_msgs" as a package, into the "common_msgs" repo, and make it a dependency of the the "common_msgs" metapackage. trajectory_msgs was added to common_msgs some time ago, so I think we're OK in that we aren't introducing any other dependencies into common_msgs (but we'd have to check a bit further to see).

Currently, if you were to change the package name from control_msgs, you're going to break pretty much every robot arm navigation and/or moveit demo ever made (since we have used control_msgs/FollowJointTrajectoryAction all over the place). I realize changing from controller_msgs to control_msgs will break some of ros_control usage, but I think at this point every user of ros_control is probably watching the repo -- the same can't be said for all users of control_msgs.

**Comment by davetcoleman** [comment]
I second the move to control_msgs

**Comment by tfoote** [comment]
It's certainly reasonable to promote these messages into common_msgs the
primary thing to say when doing this is that they are going to be stable.

It doesn't technically require moving the repository, but for clarity it
could be considered.

**Comment by davetcoleman** [comment]
Let's try to get this in before the freeze date next week. Mike are you going to work on this?

**Comment by mikeferguson** [comment]
@tfoote I would propose for Hydro, we leave control_msgs as a unary package under ros-planning or ros-controls organizatoin, and perhaps plan to move it into common_msgs for I-turtle, it's a bit late in the cycle for Hydro, by the I-turtle release it should be 100% ready.

@davetcoleman I'm unfortunately booked up for the weekend and most of early next week, so it would probably be best if someone else hopped on this to make sure it happens in time.

**Comment by isucan** [comment]
control_msgs was moved to ros-control, but controllers_msgs is still around. Perhaps we can delete controllers_msgs in Hydro? I agree with @mikeferguson on postponing the move to common_msgs until I-Turle at least.

**Comment by davetcoleman** [comment]
I have removed controller_msgs here https://github.com/ros-controls/ros_controllers/pull/30

**Comment by davetcoleman** [comment]
... i sent the pull request the exact moment @isucan commented the last comment :)

**Comment by isucan** [comment]
Now that is quite fast @davetcoleman ! I am impressed ;)

**Comment by davetcoleman** [comment]
This has been released into the public hydro debians.
