### ISSUE TITLE
Release 0.5.3

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_controllers#40]
I think the joint_trajectory_controller is ready for prime time, so I prepared the 0.5.3 release, but since I don't have push access to the [ros_controllers gbp](https://github.com/ros-gbp/ros_controllers-release), I can't do the final bloom release step

```
bloom-release ros_controllers --track hydro --rosdistro hydro
```

So, could someone with push access ( @ahendrix, @davetcoleman ) either:
- Grant me push access, or
- Run the above `bloom-release` command in my stead.

**Comment by davetcoleman** [comment]
I've given you push access.

I'm also testing the latest changes atm on my Hydro machine (pending).

**Comment by adolfo-rt** [comment]
Thanks, [rosdistro PR](https://github.com/ros/rosdistro/pull/1999).
