### ISSUE TITLE
[joint_trajectory_controller] Backport pointer fix to kinetic

### ISSUE THREAD

**Issue by edenfrosst** [ros-controls/ros_controllers#415]
Trying to implicitly convert `boost::shared_ptr` to `bool` (correctly) fails under Clang. GCC allows this, despite the conversion operator being declared `explicit`. #394 fixed this for melodic, but the change needs to be cherry-picked back into kinetic.

**Comment by matthew-reynolds** [comment]
@bmagyar Gentle bump

**Comment by bmagyar** [comment]
Backport here: https://github.com/ros-controls/ros_controllers/pull/444
Please review :) (Note: kinetic builds don't use C++11/14 by default and I wouldn't add that at this point in time)

**Comment by edenfrosst** [comment]
Fixed in #444
