### ISSUE TITLE
Invoking "cmake" failed

### ISSUE THREAD

**Issue by Desoky01** [ros-controls/ros_controllers#436]
-- +++ processing catkin metapackage: 'ros_controllers'
-- ==> add_subdirectory(ros_controllers/ros_controllers)
-- +++ processing catkin package: 'rqt_joint_trajectory_controller'
-- ==> add_subdirectory(ros_controllers/rqt_joint_trajectory_controller)
-- +++ processing catkin package: 'forward_command_controller'
-- ==> add_subdirectory(ros_controllers/forward_command_controller)
-- Could NOT find controller_interface (missing: controller_interface_DIR)
-- Could not find the required component 'controller_interface'. The following CMake error indicates t                                                                  hat you either need to install the package with the same name or change your environment so that it ca                                                                  n be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "controller_interface" with any of the following names:

    controller_interfaceConfig.cmake
    controller_interface-config.cmake

  Add the installation prefix of "controller_interface" to CMAKE_PREFIX_PATH
  or set "controller_interface_DIR" to a directory containing one of the
  above files.  If "controller_interface" provides a separate development
  package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  ros_controllers/forward_command_controller/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by bmagyar** [comment]
For "how to get started with ROS" or similar questions please go to [ROS Answers](https://answers.ros.org/).
