### ISSUE TITLE
Ackermann steering controller with real hardware

### ISSUE THREAD

**Issue by mhaboali** [ros-controls/ros_controllers#438]
Currently, I'm implementing a steering mobile robot for my graduation project and I'm wondering how to use the ackermann steering controller with my hardware. 

_**Details:**_
---------
The robot's driving wheels are the rear wheels with 2 DC-brushed motors connected to motor driver which's connected to arduino and the steering system is composed of an DC-brushed motor with absolute encoder connected to arduino board. And I don't have an URDF model for this robot.

How could I setup the ackermann steering controller with this system? and
What's the difference between the ackermann controller and PID controller from the ros pkg pid?
(To use two pid_controller nodes one for driving speed and another for steering angle)

I've searched too much about a solution but I couldn't grab clear solution that helps me.
Your help will be very appreciated,
Thanks!

**Comment by bmagyar** [comment]
Please ask this type of stuff at [ROS Answers](https://answers.ros.org/), as you can see from the delay of this message, we typically don't have time to do this sort of stuff here :)
