### ISSUE TITLE
Should we use the RealtimePublisher in diffbot.cpp?

### ISSUE THREAD

**Issue by bxc237** [ros-controls/ros_controllers#445]
Hi, in the diffbot example, should we use the RealtimePublisher here https://github.com/ros-controls/ros_controllers/blob/b480d5f06568b31b8c68a54de8042e1d63d01534/diff_drive_controller/test/diffbot.cpp#L49 to ensure that the 'while' loop running the controller's update function is realtime safe?

**Comment by bmagyar** [comment]
Good question! The answer is no, we don't need that sort of guarantee here as this is merely a test node.

**Comment by bxc237** [comment]
Thanks! Close issue...
