### ISSUE TITLE
velocity_rolling_window_size not documenten for diff_drive_controller

### ISSUE THREAD

**Issue by wilcobonestroo** [ros-controls/ros_controllers#449]
The parameter `velocity_rolling_window_size` is used in the diff_drive_controller. However, there is no documentation about that parameter on [the diff drive controller wiki](http://wiki.ros.org/diff_drive_controller).

**Comment by RobertBlakeAnderson** [comment]
I was just wondering this as well. Looking into the source code, it appears that this param sets the window size for a rolling mean, such that the controller will average the last X number of twist messages.

**Comment by matthew-reynolds** [comment]
I've added the parameters to the `diff_drive_controller` and `ackerman_steering_controller` wikis. It looks like the `four_wheel_steering_controller` doesn't have a wiki yet (See #566).
