### ISSUE TITLE
Upcoming Melodic release

### ISSUE THREAD

**Issue by bmagyar** [ros-controls/ros_controllers#456]
Holding until this list is merged:
* https://github.com/ros-controls/ros_controllers/pull/451
* https://github.com/ros-controls/ros_controllers/pull/283
* https://github.com/ros-controls/ros_controllers/pull/452

@seanyen @matthew-reynolds @ipa-mdl please comment/contribute to getting them merged/suggest others

**Comment by matthew-reynolds** [comment]
- WIP: ros-controls/ros_control#404 equivalent. Like #451, I want to do a thorough pass of the deps to make sure we're not missing anything in here after the `ros_control` cleanup.

**Comment by bmagyar** [comment]
The NaN check did not make the new release, thanks to everyone contributing!

https://github.com/ros/rosdistro/pull/24002
