### ISSUE TITLE
Joint Trajectory Controller Action Aborting

### ISSUE THREAD

**Issue by davetcoleman** [ros-controls/ros_controllers#46]
When sending follow_joint_trajectory commands to the joint_trajectory_controller, the controller only slightly perturbs the robot (in Gazebo simulation) before silently setting the action to aborted. The output information is not very obvious so I could use some pointers in what is going on...

```
DEBUG ros.joint_trajectory_controller.actionlib: The action server has received a new goal request
DEBUG ros.joint_trajectory_controller: Figuring out new trajectory starting at time 785.600
DEBUG ros.joint_trajectory_controller: Using alternate time base. In it, the new trajectory starts at time 784.825
 WARN ros.joint_trajectory_controller: Dropping first 1 trajectory points out of 62, as they occur before the specified time.
DEBUG ros.joint_trajectory_controller: Trajectory has 62 segments:
- 1 segments will still be executed from current trajectory.
- 1 segment for transitioning between the current trajectory and first point of the input message.
- 60 new segments (61 points) taken from the input message.
DEBUG ros.joint_trajectory_controller.actionlib: Accepting goal, id: /move_group-8-785.598000000, stamp: 785.60
DEBUG ros.joint_trajectory_controller.actionlib: Setting status to aborted on goal, id: /move_group-8-785.598000000, stamp: 785.60
DEBUG ros.joint_trajectory_controller.actionlib: Publishing result for goal with id: /move_group-8-785.598000000 and stamp: 785.60
```

**Comment by adolfo-rt** [comment]
When the controller is working as expected, there are only two ways to reach the ABORTED terminal state, and this is when either [path](https://github.com/ros-controls/ros_controllers/blob/hydro-devel/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h#L188) or [goal](https://github.com/ros-controls/ros_controllers/blob/hydro-devel/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h#L220) tolerances are violated. Tolerance checking is done in realtime, so I can't log from there. What you can do instead is to check the goal handle [error code](https://github.com/ros-controls/control_msgs/blob/master/control_msgs/action/FollowJointTrajectory.action#L29), which should be informative enough.

The first thing would be to check if you have very strict tolerances, or a controller with tracking issues. We can review the former by inspecting your controller configuration file, and the latter by inspecting the output of the `controller/state` topic, which outputs the tracking error among other things.

Am I understanding correctly that  your trajectory gets aborted right away?. If so, then it's path tolerances that are being violated.

Of course, there is also the possibility of an implementation bug that has not yet surfaced in the tests so far. Which hardware interface are you using?.

**Comment by davetcoleman** [comment]
I believe the issue was the PID sign was incorrect
https://github.com/ros-controls/ros_controllers/commit/d9e60c7aa586a1ad08b29277c2c5c6b3fbe91b4f
