### ISSUE TITLE
Joint Trajectory Controller which controls for Position through a velocity interface

### ISSUE THREAD

**Issue by jbeck28** [ros-controls/ros_controllers#502]
I have a robot with a velocity interface, and so have been using the Joint Trajectory Controller with velocity interface. However, it has become a bit evident that a position controller might yield better performance for my application. I'm curious if there is any implementation of a Joint Trajectory Controller which controls for position targets, through a velocity interface?

**Comment by bmagyar** [comment]
It's the same controller, just loaded with a different prefix to use different interfaces:
https://github.com/ros-controls/ros_controllers/blob/noetic-devel/joint_trajectory_controller/test/rrbot_controllers.yaml#L2

https://github.com/ros-controls/ros_controllers/blob/noetic-devel/joint_trajectory_controller/test/rrbot_vel_controllers.yaml#L2
