### ISSUE TITLE
diff_drive_controller with 'has_jerk_limits: true' option has oscillation movement of robot.

### ISSUE THREAD

**Issue by byeongkyu** [ros-controls/ros_controllers#507]
Ubuntu 18.04.4 LTS
ROS Melodic

When I enabled the option 'has_jerk_limits' in diff_drive_controller, the robot always has oscillation at stopped continuously.
I had set the options as below:

```  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.8  # m/s^2
      has_jerk_limits        : true
      max_jerk               : 2.0
```

I tried the max_jerk value to more bigger, the robot's oscillation period is reduced. But it has a oscillation too.
![jerk_option](https://user-images.githubusercontent.com/6274374/91686739-14389e80-eb99-11ea-994f-442f81f8d134.png)

**Comment by matthew-reynolds** [comment]
This just looks like a tuning issue in the controller & limiter. I'm going to close this issue, feel free to open if you feel there's a larger issue at play.
