### ISSUE TITLE
Use GitHub Actions over Travis

### ISSUE THREAD

**Issue by matthew-reynolds** [ros-controls/ros_controllers#539]
With travis-ci.org finally being shut down this month in favor of travis-ci.com, lots of jobs are taking a long time to queue ([See this support thread](https://travis-ci.community/t/builds-hang-in-queued-state/10250)) and we'll have to migrate by the end of the month anyways.

We should either migrate all the ros1 repos to travis-ci.com ([Instructions here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository)) or, more likely, switch to GitHub Actions like the ros2 repos use. Should be a pretty minor change either way given industrial_ci's support for both.

@bmagyar Not sure if this is something I can help with since these CI things are more in the hands of the repo owners, but let me know if I can help in any way.

**Comment by bmagyar** [comment]
We've been using GH actions on `ros2_control` with `industrial_ci` (!) without issues. I was under the impression that with gh actions there's no explicit repo owner procedure anymore, it's on if there's a config file for it.

here's what we use in `ros2_control` for reference
https://github.com/ros-controls/ros2_control/blob/master/.github/workflows/ci.yml
