### ISSUE TITLE
FindPackage xacro in groovy 

### ISSUE THREAD

**Issue by bbrieber** [ros-controls/ros_controllers#56]
Hi,

I just updated my package and recognized that catkin_make did not work anymore under groovy (I have no idea if it runs with hydro...). 

The problem is that there is no FindXacro which is needed for FindPackage
I solved the problem on my machine by commenting out the xacro from the FindPackage call (Line 67) 

for me it seems like xacro is not needed as package (the catkin dependency works...) so it can surely be removed...   

greetings 

Benjamin

**Comment by davetcoleman** [comment]
I already requested to remove it in this issue https://github.com/ros-controls/ros_controllers/pull/44

This branch has the fix https://github.com/ros-controls/ros_controllers/tree/groovy-backported-hydro
