### ISSUE TITLE
where is the "#include <four_wheel_steering_msgs/FourWheelSteeringStamped.h>"?

### ISSUE THREAD

**Issue by nonlinear1** [ros-controls/ros_controllers#583]
I check the "https://github.com/ros-controls/control_msgs", I cann't find the definition for the msg "four_wheel_steering_msgs".
Could someone know where this msg comes from? or It haven't been implimented?
Thanks and best regards for you

**Comment by destogl** [comment]
https://github.com/ros-drivers/four_wheel_steering_msgs

The detailed answer: https://is.gd/7N9VFM
