### ISSUE TITLE
Joint trajectory controller: Change default for stop_trajectory_duration parameter.

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_controllers#73]
The `stop_trajectory_duration` parameter of the controller currently defaults to 0.5s. I think it would be best to default it to zero. Since this potentially changes behavior, should I defer the change to Indigo or can it be considered small enough to make it to Hydro?.

Parameter doc follows:

> When starting the controller or canceling a trajectory, position hold mode is entered. This parameter specifies the time it takes to bring the current state (position and velocity) to a stop. Its value can be greater or equal than zero.

**Comment by jim-rothrock** [comment]
I say change it now.

**Comment by davetcoleman** [comment]
I don't think it would affect any of my use cases, and it can always be
over written by controller settings.

On Thursday, December 12, 2013, Jim Rothrock wrote:

> I say change it now.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-controls/ros_controllers/issues/73#issuecomment-30387806
> .

## 

:: dave | 251.463.2345 c
