### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by adolfo-rt** [ros-controls/ros_controllers#80]
All,

I'd like to release ros_controllers 0.6.1 into hydro, to make the `diff_drive_controller` and `gripper_action_controller` packages available as binaries. Are there any blockers against releasing before the end of the week?.

I'd also like to do the initial indigo release soon, but it can be done after dealing with hydro.

**Comment by davetcoleman** [comment]
+1

**Comment by adolfo-rt** [comment]
It will be in fact 0.7, as we're talking about big new additions, not small bugfixes.

**Comment by adolfo-rt** [comment]
Finally. In ros/rosdistro#3652.
